test

diff --git a/.github/workflows/detect-secrets.yml b/.github/workflows/detect-secrets.yml
--- a/.github/workflows/detect-secrets.yml
+++ b/.github/workflows/detect-secrets.yml
@@ -1,9 +1,9 @@
 name: Detect Secrets
 
-on:  
-  pull_request:  
-    branches: [main]  
-  push:  
+on:
+  pull_request:
+    branches: [main]
+  push:
     branches: [main]
 
 jobs:
@@ -43,17 +43,16 @@ jobs:
           echo "Debugging: Contents of new_scan.json"
           cat new_scan.json
 
-          # Compare the new scan with the baseline to detect new secrets
-          NEW_SECRETS=$(detect-secrets audit new_scan.json --json | jq '.results | length')
+          # Compare the new scan with the baseline to detect any secrets
+          ALL_SECRETS=$(detect-secrets audit new_scan.json --json | jq '.results | length')
 
-          if [ "$NEW_SECRETS" -gt 0 ]; then
-            echo "⚠️ Warning: New secrets detected! See details below:"
-
+          if [ "$ALL_SECRETS" -gt 0 ]; then
+            echo "⚠️ Warning: Secrets detected! See details below:"
+            
             # Output detailed information about the secrets found, including filename and line number
             detect-secrets audit new_scan.json --json | jq -r '.results[] | "\(.filename):\(.line_number) - Secret: \(.secret)"'
 
             echo "Update the baseline if necessary!"
-            exit 1  # Fail the pipeline if new secrets are found
+            exit 1  # Fail the pipeline if any secrets are found
           else
-            echo "✅ No new secrets detected. Proceeding..."
-          fi
+            echo "✅ No secrets detected. Proceeding..."
