oppdatert baseline fil

diff --git a/.github/workflows/detect-secrets.yml b/.github/workflows/detect-secrets.yml
--- a/.github/workflows/detect-secrets.yml
+++ b/.github/workflows/detect-secrets.yml
@@ -14,27 +14,25 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          submodules: false  # Unngå kloning av submoduler
+          submodules: false  # Avoid cloning submodules
 
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.10'  # Bruk versjonen du har installert
+          python-version: '3.10'  # Use the installed Python version
 
       - name: Install detect-secrets
-        run: |
-          pip install detect-secrets
+        run: pip install detect-secrets
 
-      - name: Run detect-secrets
+      - name: Run detect-secrets scan
+        run: detect-secrets scan --baseline .secrets.baseline
+
+      - name: Check for new secrets
         run: |
-          detect-secrets scan --baseline .secrets.baseline
-      
-      - name: New secrets found
-      run: |
-       detect-secrets scan --baseline .secrets.baseline > new_scan.json
-       if ! diff .secrets.baseline new_scan.json; then
-        echo "⚠️ Warning: New secrets detected! See details below:"
-        detect-secrets scan | grep '"filename"' -A 3  # Shows filename and line number
-        echo "Update the baseline if necessary!"
-        exit 1  # Fails the pipeline if new secrets are found
-       fi
+          detect-secrets scan --baseline .secrets.baseline > new_scan.json
+          if ! diff .secrets.baseline new_scan.json; then
+            echo "⚠️ Warning: New secrets detected! See details below:"
+            detect-secrets scan | grep '"filename"' -A 3  # Shows filename and line number
+            echo "Update the baseline if necessary!"
+            exit 1  # Fails the pipeline if new secrets are found
+          fi
