oppdatert baseline fil

diff --git a/.github/workflows/detect-secrets.yml b/.github/workflows/detect-secrets.yml
--- a/.github/workflows/detect-secrets.yml
+++ b/.github/workflows/detect-secrets.yml
@@ -30,9 +30,11 @@ jobs:
           detect-secrets scan --baseline .secrets.baseline
       
       - name: New secrets found
-        run: |
-          detect-secrets scan --baseline .secrets.baseline > new_scan.json
-          if ! diff -q .secrets.baseline new_scan.json; then
-            echo "New secrets found. Update basline if necesarry!"
-            exit 1
-          fi
+      run: |
+       detect-secrets scan --baseline .secrets.baseline > new_scan.json
+       if ! diff .secrets.baseline new_scan.json; then
+        echo "⚠️ Warning: New secrets detected! See details below:"
+        detect-secrets scan | grep '"filename"' -A 3  # Shows filename and line number
+        echo "Update the baseline if necessary!"
+        exit 1  # Fails the pipeline if new secrets are found
+       fi
