TF:Lint

diff --git a/.github/workflows/pw.7.1.yml b/.github/workflows/pw.7.1.yml
--- a/.github/workflows/pw.7.1.yml
+++ b/.github/workflows/pw.7.1.yml
@@ -20,4 +20,9 @@ jobs:
     - name: Lint Terraform Code
       run: |
         tflint --recursive > tflint_output.txt
+        if [ $? -ne 0 ]; then
+          echo "Linting failed"
+          cat tflint_output.txt
+          exit 1
+        fi
         cat tflint_output.txt
