Working on OPA

diff --git a/.github/workflows/pw.9.2.yml b/.github/workflows/pw.9.2.yml
--- a/.github/workflows/pw.9.2.yml
+++ b/.github/workflows/pw.9.2.yml
@@ -76,13 +76,24 @@ jobs:
       run: |
         cat tfplan.json
  
+    - name: Verify OPA Installation
+      run: |
+          if ! command -v opa &> /dev/null; then
+            echo "OPA is not installed or not found in PATH."
+            exit 1
+          else
+            echo "OPA is installed correctly."
+            opa version
+          fi
+
     - name: Run OPA Policy Check
       run: |
-        violations=$(opa eval --data policies/ --input tfplan.json --format pretty "data.terraform.security.deny")
-        if [ "$violations" != "[]" ]; then
-           echo "OPA policy violations found!"
-           echo "$violations"
-           exit 1
-        else
-          echo "No OPA violations found."
-        fi
+          violations=$(opa eval --data policies/ --input tfplan.json --format pretty "data.terraform.security.deny")
+          echo "$violations"
+          if [ "$violations" != "[]" ]; then
+             echo "OPA policy violations found!"
+             echo "$violations"
+             exit 1
+          else
+            echo "No OPA violations found."
+          fi
