Reused code from other workflow

diff --git a/.github/workflows/pw.9.2.yml b/.github/workflows/pw.9.2.yml
--- a/.github/workflows/pw.9.2.yml
+++ b/.github/workflows/pw.9.2.yml
@@ -8,23 +8,60 @@ on:
 jobs:
   Setup-terraform:
     runs-on: ubuntu-latest
+env:
+  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
+  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+
+jobs:
+  terraform-plan:
+    name: 'Terraform Plan'
+    runs-on: ubuntu-latest
+    env:
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
+    # Log in to azure CLI
+    - name: Azure CLI Login
+      uses: azure/login@v2
+      with:
+        client-id: ${{ env.ARM_CLIENT_ID }}
+        tenant-id: ${{ env.ARM_TENANT_ID }}
+        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.0.11
+    # Install the latest version of the Terraform CLI
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+      with:
+        terraform_wrapper: false
 
-      - name: Install OPA
-        run: wget https://openpolicyagent.org/downloads/latest/opa_linux_amd64 -O opa && chmod +x opa && mv opa /usr/local/bin/
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
 
-      - name: Run Terraform Init
-        run: terraform init -backend=false
-      - name: Terraform plan
-        run: terraform plan -out=tfplan.binary
+    #Create tfvars file
+    - name: Create terraform.tfvars
+      run: | 
+        echo "admin_password=\"Cisco123!\"" >> terraform.tfvars
 
-      - name: Write out Terraform plan
-        run: cat tfplan.json
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
